version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    image: semtech/mu-identifier:1.7.0
    labels:
      - "logging=true"
    ports:
      - 80:80
    restart: "no"
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:1.1.2
    volumes:
      - ./config/dispatcher:/config
    restart: "no"
    logging: *default-logging
    labels:
      - "logging=true"
  virtuoso:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    logging: *default-logging
  resource:
    image: semtech/mu-cl-resources:1.18.0
    volumes:
      - ./config/resources:/config
    logging: *default-logging
    labels:
      - "logging=true"
  migrations:
    image: semtech/mu-migrations-service
    links:
      - virtuoso:database
    volumes:
      - ./config/migrations:/data/migrations

    logging: *default-logging
  deliver-email-service:
    image: redpencil/deliver-email-service:0.1.1
    ports:
      - 8888:80
      - 9229:9229
    environment:
      SECURE_CONNECTION: "true"
      NODE_ENV: "development"
      EMAIL_PROTOCOL: "smtp"
      WELL_KNOWN_SERVICE: "gmail"
      EMAIL_ADDRESS: "mymail@myservice.com"
      EMAIL_PASSWORD: "myemailpassword"
      FROM_NAME: "myname"
    labels:
      - "logging=true"
    restart: always
    volumes:
      - /path/to/local/cloned/deliver-email-service/folder/:/app/
    logging: *default-logging
  database:
    image: semtech/mu-authorization:0.6.0-beta.5
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
    labels:
      - "logging=true"
    volumes:
      - ./config/authorization:/config
    logging: *default-logging
  file:
    image: semtech/mu-file-service:3.1.0
    links:
      - virtuoso:database
    volumes:
      - ./data/files:/share
