version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    image: semtech/mu-identifier:1.7.0
    labels:
      - "logging=true"
    restart: "no"
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:1.1.2
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    restart: "no"
    logging: *default-logging
  virtuoso:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    logging: *default-logging
  resource:
    image: semtech/mu-cl-resources:1.18.0
    volumes:
      - ./config/resources:/config
    logging: *default-logging
  migrations:
    image: semtech/mu-migrations-service
    links:
      - virtuoso:database
    volumes:
      - ./config/migrations:/data/migrations
    logging: *default-logging
  deliver-email-service:
    image: delivery-email-service-test_1
    ports:
      - 8888:80
      - 9229:9229
    environment:
      NODE_ENV: "development"
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
    volumes:
      - /media/achraf/Main/Work/RedPencil/Services/deliver-email-service/:/app/
  database:
    image: semtech/mu-authorization:0.6.0-beta.5
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
    volumes:
      - ./config/authorization:/config